### PR TITLE
Fix ffi_lib missing on Windows

### PR DESCRIPTION
**Pull request by agross**
Closes headius/spoon#17 and probably rsense/rsense#36

### CODE REVIEW

**Comment by headius** [comment]
Sorry I did not notice this!

**Comment by brendon** [comment]
This fixed the problem for me :) Are you able to merge this?

**Comment by orta** [comment]
Would love to see rsense working on windows for [vscode](https://github.com/rubyide/vscode-ruby/issues/34), any chance this can get merged + released?

**Comment by ivanovaleksey** [comment]
@agross thank you so much! It should be merged!

**Comment by agross** [comment]
@headius, can you please notice this PR once more? ;-)

**Comment by headius** [comment]
Released in 0.0.5.

**Comment by ivanovaleksey** [comment]
Thank you very much!

**Comment by Szandor72** [comment]
I still got the same issue with Spoon/rsense despite the recent update :(

```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoo
n::FileActions (NameError)
Did you mean?  FileUtils
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:12:in `<top (required)>'
        from C:/Ruby23/bin/rsense:22:in `load'
        from C:/Ruby23/bin/rsense:22:in `<main>'
```

**Comment by ivanovaleksey** [comment]
@Szandor72 you are using [rsense-0.5.18](https://github.com/rsense/rsense/blob/v0.5.18/rsense.gemspec#L23) which locks `spoon ~> 0.0.4`. 
As you can see the issue is closed in spoon `0.0.5`.

**Comment by Szandor72** [comment]
Thanks for pointing that out. 

I miserably failed for the last hour trying to download rsense master, edit the .gemspec, update the spoon dependency, and do a rake install - all I get is an empty rsense folder. So no auto complete in atom for ruby.

**Pull request merged**
